export const SET_HOMEPAGE_FEEDS = "SET_HOMEPAGE_FEEDS";
export const SET_USER_FEEDS = "SET_USER_FEEDS";

export const SET_USER = "SET_USER";
export const SET_CHAT_TARGET_USER = "SET_CHAT_TARGET_USER";
export const SET_USER_FRIEND_REQUESTS = "SET_USER_FRIEND_REQUESTS";
export const SET_USER_FRIENDS = "SET_USER_FRIENDS";
export const SET_SEARCHED_USERS = "SET_SEARCHED_USERS";
export const RESET_SEARCHED_USERS = "RESET_SEARCHED_USERS";
export const SET_ADMIN_USERS = "SET_ADMIN_USERS";
export const SET_ADMIN_USER = "SET_ADMIN_USER";

export const SET_CHAT = "SET_CHAT";
