export const SET_HOMEPAGE_FEEDS = "SET_HOMEPAGE_FEEDS";
export const SET_USER_FEEDS = "SET_USER_FEEDS";

export const SET_USER = "SET_USER";
export const SET_USER_FRIEND_REQUESTS = "SET_USER_FRIEND_REQUESTS";
